services:
  backend-app:
    container_name: backend-app
    build: 
      context: ../backend
    ports:
      - '8080:8080'
    volumes:
      - ../backend:/app
    working_dir: /app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=sample_db
    depends_on:
      - mysql
    command:  ["node", "index.js"]

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sample_db
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
